### ISSUE TITLE
Missing dependecies when deploy to vercel

### ISSUE THREAD

**Issue by anhzf** [restuwahyu13/midtrans-node#39]
The errors occur when I'm deploying to vercel, I thought the errors come from the internal package (midtrans-node)
thank you.

```
[GET] /api/midtrans						19:56:20:44
2021-03-11T12:56:21.229Z	undefined	ERROR	Cannot find module 'lodash'
Require stack:
- /var/task/node_modules/midtrans-node-client/dist/lib/apiConfig.js
- /var/task/node_modules/midtrans-node-client/dist/lib/coreApi.js
- /var/task/node_modules/midtrans-node-client/dist/index.js
- /var/task/api/midtrans.ts
- /var/task/___vc_launcher.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
2021-03-11T12:56:21.230Z	undefined	ERROR	Did you forget to add it to "dependencies" in `package.json`?
RequestId: 3cfb66b5-7cc6-4f46-ad52-76d4ee5f85d9 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by restuwahyu13** [comment]
thank you for this problem, okay I will fix it soon

**Comment by anhzf** [comment]
> looks like the problem is because I am using the umd module so the lodash module is not readable, try using **version 0.0.5** I have fixed it, please report if the same thing happens, now you can use this module support for mobile, browser, and server

okay, I'll try it. thank you for ur help
